#project identification
sonar.host.url=https://sonarcloud.io
sonar.projectKey=Computime-OSS_ocpp
sonar.projectName=OCPP-HEMS-connector
sonar.organization=computime-oss
sonar.projectVersion=1.0.0

#source layout
sonar.sources=custom_components/ocpp
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12

#Coverage
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.bandit.reportPaths=bandit-report.json

# Exclusions — non-code folders
sonar.exclusions=**/.venv/**,\
  **/__pycache__/**,\
  **/*.pyc,\
  docs/**,\
  scripts/**,\
  manage/**,\
  config/**
sonar.coverage.exclusions=**/tests/**
